# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.1
maven_group = com.davidblackcn
archives_name = lorian-arch-orbit
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# Dependencies
architectury_api_version = 21.0.7
fabric_loader_version = 0.19.3
fabric_api_version = 0.157.0+26.2
neoforge_version = 26.2.0.52-beta
yacl_version = 3.9.6
mod_menu_version = 20.0.1
junit_version = 5.14.4
junit_platform_version = 1.14.4
gson_version = 2.14.0
